import React from 'react'
import NavBar from '../NavBar/NavBar'
import CardProyects from './CardProyects'

function Proyects() {
    const myProyects = [
        { name: "Reservation Platform FrontEnd", tittle: "ReactJS - APIs - Bootstrap", about: "Final project for the subject 'Programming Laboratory III'. An interactive platform was created so that users can make reservations in recreational establishments. Developed in the React library using JavaScript, HTML and CSS. Complemented with Toasty, Bootstrap. Making requests to a 'Fake API', which returns the profiles, establishments and shifts.", repositoryurl: "https://github.com/salinasariel/TUP-LC3TT-G13", videourl: "https://www.linkedin.com/feed/update/urn:li:activity:7083950503851696128/", deployurl: "https://lc3proyect.web.app/"},
        { name: "Portfolio FullStack", tittle: "AngularTS - Spring", about: "Integrative project of the 'Yo Programo' course of the official government program 'Argentina Programa'. The project consisted of using what was learned in HTML, CSS and TypeScript to develop a FrontEnd with the Angular Framework. A Spring Backend was also developed to respond to requests generated by the user.", repositoryurl: "https://github.com/salinasariel/Proyecto_AP_Salinas", videourl: "https://www.linkedin.com/feed/update/urn:li:activity:7066449283524308992/", deployurl: "" },
        { name: "Online price calculator", tittle: "HTML - CSS -JavaScript (Vanilla proyect)", about: "Project extracted from an exam for the final approval of the subject 'Computer Laboratory II' of my career at the National Technological University. The exam consisted of developing an interactive budget application in a maximum time of one hour and a half.", repositoryurl: "https://github.com/salinasariel/cotizador_online", videourl: "", deployurl: "https://salinasariel.github.io/cotizador_online/" }, 
        
       ]
    const ProyectsList = myProyects.map((v) =>{
        return <CardProyects name= {v.name} tittle= {v.tittle} about= {v.about} repositoryurl= {v.repositoryurl} videourl= {v.videourl} deployurl= {v.deployurl} />
    })

    
    return (
        <div>
            
            <div className='content scale-up-center'>
                <h1>My Proyects 👨‍💻</h1>
                
                {ProyectsList}
            </div>
        </div>
    )
}

export default Proyects